config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :stock_level_adjustments
    resources :products
    resources :orders do
      member do
        get :ship
        get :accept
        get :reject
      end
    end
    resources :articles do
      member {post :like}
    end
    resources :promotions
    resources :tax_rates
    resources :users
    resources :countries
    resources :addresses
    resources :currencies
    resources :product_categories
    resources :payments, only: [:new, :create] do
      member do
        get :confirm
      end
    end
    resources :delivery_services do
      resources :delivery_service_prices
    end
  end
  resources :comments do
    member {post :like}
  end

  get '/admin', to: "admin/products#index"

  scope "(:locale)",locale: /#{I18n.available_locales.join("|")}/ do
  
    resources :user_sessions, only: [:new, :create]
    resources :password_resets
    get '/store/:permalink', to: "public#show", as: :item
    get '/home', to: "public#index", as: :home
    get '/store', to: "public#store", as: :store
    get "/login" => "user_sessions#new", as: :login
    get "/register" => "admin/users#register", as: :register
    get "/logout" => "user_sessions#destroy", as: :logout
    get 'user_sessions/create'
    get 'user_sessions/destroy'
    get '/cart', to: "cart#index", as: :cart
    get '/add', to: "cart#add", as: :add
    get '/clear', to: "cart#clear", as: :clear
    get '/remove', to: "cart#remove", as: :remove
    get '/set-address/(:delivery)/(:token)', to: "admin/addresses#new", as: :set_address
    get '/set-delivery/(:token)', to: "process#delivery", as: :set_delivery
    get '/blog', to: "blog#blog", as: :blog
    get '/blog/:permalink', to: "blog#article", as: :blog_article
    get '/about', to: "public#about", as: :about
    get '/contact', to: "public#contact", as: :contact
    get '/payment/:token', to: "admin/payments#new", as: :purchase
    get '/terms', to: "public#terms", as: :terms
    root 'public#index'
  end
  match '', to: redirect("/#{I18n.default_locale}/home"), :via => [:get]
  match 'admin/:controller(/:action(/:id))', :via => [:get, :post, :patch]

end

app/models/article.rb
class Article < ActiveRecord::Base
	#relationships
	belongs_to :admin, class_name: "User"
	has_many :comments
    has_many :attachments, :as => :parent, :dependent => :destroy, :autosave => true
    has_many :evaluations, class_name: "RSEvaluation", as: :target

    has_reputation :likes, source: :user, aggregated_by: :sum

    #validations
    validates :title, presence: true
    validates :content, presence: true
    validates :permalink, presence: true ,
                          uniqueness: true
    # validates :admin, presence: true
    validates :pub_date, presence: true

    # globalize gem initialization
    translates :title, :content

    # Nested attributes for attachments
    accepts_nested_attributes_for :attachments, allow_destroy: true 

    # Before validation, set the permalink if we don't already have one
    before_validation { self.permalink = self.title.parameterize if self.permalink.blank? && self.title.is_a?(String) }
    
    #All published articles
    scope :published, -> {where(visible: true)}
    scope :ordered, -> {order(:pub_date => :desc)}
    
    def has_attachments?
      self.attachments.count > 0 
    end

    #determines wether user has liked an item already
    def was_liked?(item)
      evaluations.where(source_type: item.class, source_id: item.id).present?
    end
    
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :set_article, only: [:update, :edit, :destroy]
  before_action :require_admin_user, except: [:like]
  before_action :require_user, only: [:like]
  layout 'admin'

	def index
	  @articles = Article.ordered.page(params[:page]).per_page(30)
	end

	def new
	  @article = current_user.articles.new
	end

  def edit
  end

	def create
	  @article = current_user.articles.new(article_params)
 	  respond_to do |format|
        if @article.save
          if params[:images]
            params[:images].each {|image|
              @article.attachments.create(file: image, parent_type: 'article')
            }
          end
          format.html { 
            flash[:success] = "A new article has been created."
            redirect_to admin_articles_path
          }

          format.js
        else
          format.html { 
            flash[:alert] = "Something went wrong."
            render action: 'new'
          }
          format.js
        end
	  end
	end

	def update
	  if @article.update_attributes(article_params)
        if params[:images]
          params[:images].each {|image|
            if !(@article.attachments.find_by_file_name(image.original_filename[0..-5].to_s).nil?)
              @article.attachments.find_by_file_name(image.original_filename[0..-5].to_s).destroy 
            end
            @article.attachments.create(file: image, parent_type: 'article')
          }
        end
        flash[:success] = "The article has been updated."
        redirect_to admin_articles_path
      else
        flash[:alert] = "Something went wrong."
      	render action: 'edit'
	  end
	end

  def destroy
    @article.destroy
    flash[:success] = "The Article has been Deleted."
    redirect_to admin_articles_path
  end

  def like
    @article = Article.find(params[:id])
    @article.add_or_update_evaluation(:likes, 1, current_user)

    respond_to do |format|
      format.html {
        redirect_to :back
      }
      format.js
    end
  end

	private
     
    def article_params
      params.require(:article).permit(:title, :permalink, :content, :admin_id, :likes, :credits, :pub_date, :visible)
    end

    def set_article
      @article = Article.find(params[:id])  
    end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/views/admin/articles/_form.html.haml
.contain
  .row
    .small-12.large-12.columns
      %label{:class => "#{error_on?(@article, :title)}"} Title
      = f.input :title, label: false
.contain
  .row
    .small-12.large-12.columns
      %label{:class => "#{error_on?(@article, :permalink)}"} Permalink
      = f.input :permalink, label: false
.contain
  .row
    .small-12.large-12.columns
      %label{:class => "#{error_on?(@article, :name)}"} Content
      = f.cktext_area :content, as: :text, label: false
.contain
  .row
    .small-12.large-12.columns
      = f.input :credits, as: :text
.contain
  .row
    .small-6.large-6.columns
      %label{:class => "#{error_on?(@article, :name)}"} Publication Date
      = f.input :pub_date, label: false, as: :date, start_year: Date.today.year, end_year: Date.today.year + 12, order: [:month, :year, :day]
    .small-6.large-6.columns
      = f.input :visible, as: :boolean, label: "Sets this as visible When checked."
.contain
  .row
    = f.label "Article Images"
  .p-images.row
    - if @article.has_attachments?
      - @article.attachments.each do |attachment|
        .p-image
          = img_tag(attachment)
          %p= attachment.file_name
    - else
      %p.no-file Upload The appropriate article images (ie: head.jpg, head.png,...)
  .row
    = file_field_tag "images[]", type: :file, multiple: true
.contain.last
  .row
    = f.button :submit, "SAVE", class: 'button small round success header-btn'
    = link_to('CANCEL', admin_articles_path(), class: 'button small dark round header-btn')

app/views/admin/articles/edit.html.haml
.cd-header.show
  =image_tag('articles.svg', id:'ar-icon')
  =image_tag('hamburger.svg', id:'menu-trigger')
  =link_to('back to articles', admin_articles_path(@article), class: 'button small round dark header-btn')
  = admin_locale_tag
  %h3.mar-left-65 Articles
= simple_form_for @article, html: {multipart: true}, url: url_for(:action => 'update', :controller => 'admin/articles'), :method => 'patch' do |f|
  = render(:partial => 'form', :locals => {:f => f})

app/views/admin/articles/index.html.haml
.cd-header.show
  =image_tag('articles.svg', id:'ar-icon')
  =image_tag('hamburger.svg', id:'menu-trigger')
  =link_to('new article', new_admin_article_path(), class: 'button small round success header-btn')
  %h3.mar-left-65 Articles
.row
  .large-2.columns
  .small-11.medium-11.large-10.columns
    %table.table
      %thead
        %tr
          %th{width: 150} Title
          %th{width: 150} Pub Date
          %th{width: 150} Author
          %th{width: 150} Visible?
          %th{width: 50} Likes
          %th{width: 50}
          %th{width: 50}
      %tboby
        - @articles.each do |article|
          %tr
            %td= link_to(article.title.titleize, edit_admin_article_path(article))
            %td= article.pub_date.strftime("%m/%d/%y")
            %td Admin
            %td= status_tag(article.visible)
            %td= article.reputation_for(:likes).to_i
            %td.delete= link_to "Delete", admin_article_path(article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"}
            %td.delete= link_to "Preview", blog_article_path(permalink: article.permalink)
    .admin-page
      = will_paginate @articles

app/views/admin/articles/like.js.erb
$("<%= j'.' + 'article_' + @article.id.to_s %>").html("<%= j @article.reputation_for(:likes).to_i.to_s %>");

app/views/admin/articles/new.html.haml
.cd-header.show
  =image_tag('articles.svg', id:'ar-icon')
  =image_tag('hamburger.svg', id:'menu-trigger')
  =link_to('back to articles', admin_articles_path(), class: 'button small round dark header-btn')
  = admin_locale_tag
  %h3.mar-left-65 Articles
= simple_form_for @article, html: {multipart: true}, url: admin_articles_path(@article), method: :post do |f|
  = render(:partial => 'form', :locals => {:f => f})