config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :stock_level_adjustments
    resources :products
    resources :orders do
      member do
        get :ship
        get :accept
        get :reject
      end
    end
    resources :articles do
      member {post :like}
    end
    resources :promotions
    resources :tax_rates
    resources :users
    resources :countries
    resources :addresses
    resources :currencies
    resources :product_categories
    resources :payments, only: [:new, :create] do
      member do
        get :confirm
      end
    end
    resources :delivery_services do
      resources :delivery_service_prices
    end
  end
  resources :comments do
    member {post :like}
  end

  get '/admin', to: "admin/products#index"

  scope "(:locale)",locale: /#{I18n.available_locales.join("|")}/ do
  
    resources :user_sessions, only: [:new, :create]
    resources :password_resets
    get '/store/:permalink', to: "public#show", as: :item
    get '/home', to: "public#index", as: :home
    get '/store', to: "public#store", as: :store
    get "/login" => "user_sessions#new", as: :login
    get "/register" => "admin/users#register", as: :register
    get "/logout" => "user_sessions#destroy", as: :logout
    get 'user_sessions/create'
    get 'user_sessions/destroy'
    get '/cart', to: "cart#index", as: :cart
    get '/add', to: "cart#add", as: :add
    get '/clear', to: "cart#clear", as: :clear
    get '/remove', to: "cart#remove", as: :remove
    get '/set-address/(:delivery)/(:token)', to: "admin/addresses#new", as: :set_address
    get '/set-delivery/(:token)', to: "process#delivery", as: :set_delivery
    get '/blog', to: "blog#blog", as: :blog
    get '/blog/:permalink', to: "blog#article", as: :blog_article
    get '/about', to: "public#about", as: :about
    get '/contact', to: "public#contact", as: :contact
    get '/payment/:token', to: "admin/payments#new", as: :purchase
    get '/terms', to: "public#terms", as: :terms
    root 'public#index'
  end
  match '', to: redirect("/#{I18n.default_locale}/home"), :via => [:get]
  match 'admin/:controller(/:action(/:id))', :via => [:get, :post, :patch]

end

app/models/order.rb
class Order < ActiveRecord::Base
	# Require dependencies
    require_dependency 'order/states'
    require_dependency 'order/actions'
    require_dependency 'order/billing'
    require_dependency 'order/delivery'

    PROMO_CODES = Promotion.visible.map(&:code) << nil

    #All items which make up this order
    has_many :order_items, :dependent => :destroy
    accepts_nested_attributes_for :order_items, :allow_destroy => true, :reject_if => Proc.new { |a| a['ordered_item_id'].blank? }
    has_many :products, :through => :order_items, :class_name => 'Product', :source => :ordered_item, :source_type => 'Product'
    belongs_to :customer, :class_name => "User"
    belongs_to :billing_address, class_name: "Address", :dependent => :destroy
    belongs_to :shipping_address, class_name: "Address", :dependent => :destroy

    # Validations
    validates :token, :presence => true
    validates :promo_code, :inclusion => {in: PROMO_CODES}
    # Set some defaults
    before_validation { self.token = SecureRandom.uuid  if self.token.blank?}
    before_validation { self.promo_code.strip}
    before_validation { self.promo_code = nil if self.promo_code.blank?}

   
    # The length of time the customer spent building the order before submitting it to us.
    # The time from first item in basket to received.
    scope :ordered, -> { order(:created_at => :desc)}
    def build_time
      return nil if self.received_at.blank?
      self.created_at - self.received_at
    end
    # Is this order empty? 
    def empty?
      order_items.empty?
    end
    # Does this order have items?
    def has_items?
      total_items > 0
    end

    # Return the number of items in the order
    def total_items
      order_items.inject(0) { |t,i| t + i.quantity }
    end

    def expired?
        return false if !self.building?
        if self.created_at.days_since(1) < Time.now
            self.state = "rejected"
            self.save!
            return true
        end
    end

end

app/models/order/actions.rb
require "error"
require "errors/insufficient_stock_to_fulfil"
class Order < ActiveRecord::Base
    extend ActiveModel::Callbacks
    # These additional callbacks allow for applications to hook into other
    # parts of the order lifecycle.
    define_model_callbacks :confirmation, :acceptance, :rejection
  
    # This method should be called by the base application when the user has completed their 
    # first round of entering details. This will mark the order as "confirming" which means
    # the customer now just must confirm.
   
    def proceed_to_confirm(params = {})
      self.state = 'confirming'
      if self.update(params)
        true
      else
        false
      end
    end
  
    # This method should be executed by the application when the order should be completed
    # by the customer. It will raise exceptions if anything goes wrong or return true if
    # the order has been confirmed successfully
  
    def confirm!
      no_stock_of = self.order_items.select(&:validate_stock_levels)
      unless no_stock_of.empty?
        raise Errors::InsufficientStockToFulfil, :order => self, :out_of_stock_items => no_stock_of
      end
     
      run_callbacks :confirmation do
      	# Mark order as received
      	self.state = 'received'
        self.received_at = Time.now
        self.save!
        self.order_items.each(&:confirm!)
        #send an email to the customer
        deliver_received_order_email
        
      end
      true
    end

    # Mark order as accepted
    def accept!
      run_callbacks :acceptance do
        self.accepted_at = Time.now
        self.state = "accepted"
        self.save!
        deliver_accepted_order_email
      end
    end

    # Mark order as rejected

    def reject!
      run_callbacks :rejection do
        self.rejected_at = Time.now
        self.state = "rejected"
        self.save!
        deliver_rejected_order_email
      end
    end
    
    def pay!
      self.payments.create!(:amount => self.amount_paid, method: "default", confirmed: false, refundable: true, reference: "Order #{self.id}")  
    end

    def deliver_accepted_order_email
      OrderMailer.accepted(self).deliver_now
    end

    def deliver_rejected_order_email
      OrderMailer.rejected(self).deliver_now
    end

    def deliver_received_order_email
      OrderMailer.received(self).deliver_now
    end

end

app/models/order/billing.rb
class Order < ActiveRecord::Base
  
  # The country which this order should be billed to
  belongs_to :billing_country, :class_name => 'Country', :foreign_key => 'billing_country_id'
  # Payments which have been stored for the order
  has_many :payments, :dependent => :destroy

  # Validations
  with_options :if => Proc.new { |o| !o.building? } do |order|
    order.validates :billing_address_id, :presence => true
  end
  
  def billing_name
     self.billing_address.full_name
  end

  def shipping_name
     self.shipping_address.full_name
  end
  # The total cost of the order
  def total_cost
    self.delivery_cost_price +
    order_items.inject(BigDecimal(0)) { |t, i| t + i.total_cost }
  end

  def items_sub_total
    order_items.inject(BigDecimal(0)) { |t, i| t + i.sub_total }
  end

  # The total amount due on the order
  #
  # @return [BigDecimal]
  def balance
    @balance ||= total - amount_paid
  end

  # Is there a payment still outstanding on this order?
  #
  # @return [Boolean]
  def payment_outstanding?
    balance > BigDecimal(0)
  end

  # Has this order been paid in full?
  #
  # @return [Boolean]
  def paid_in_full?
    !payment_outstanding?
  end

  # Is the order invoiced?
  #
  # @return [Boolean]
  def invoiced?
    !invoice_number.blank?
  end

end

app/models/order/delivery.rb
require "error"
require "errors/inapropriate_delivery_service"
class Order < ActiveRecord::Base
  #The associated delivered service
  belongs_to :delivery_service
  # The country where this order is being delivered to (if one has been provided)
  belongs_to :delivery_country, :class_name => 'Country', :foreign_key => 'delivery_country_id'
  
  # Set up a callback for use when an order is shipped
  define_model_callbacks :ship

  # Validations
  with_options :if => :separate_delivery_address? do |order|
    order.validates :shipping_address_id, :presence => true
  end

  validate do
    if self.delivery_required?
      if self.delivery_service.nil?
      	 errors.add :delivery_service_id, :must_be_specified
      elsif !self.valid_delivery_service?
        errors.add :delivery_service_id, :not_suitable
      end
    end
  end

  before_confirmation do
    # Ensure that before we confirm the order that the delivery service which has been selected
    # is appropritae for the contents of the order.
    if self.delivery_required? && !valid_delivery_service?
      raise Errors::InapropriateDeliveryService, :order => self
    end
  end

    # Create some delivery_ methods which will mimic the billing methods if the order does
    # not need a seperate address.
    [:delivery_name, :delivery_address1, :delivery_address2, :delivery_address3, :delivery_address4, :delivery_postcode, :delivery_country].each do |f|
      define_method(f) do
        separate_delivery_address? ? super() : send(f.to_s.gsub('delivery_', 'billing_'))
      end
    end

    def shipped?
      !!self.shipped_at?
    end

    def delivery_country
      self.separate_delivery_address ? self.shipping_address.country : self.billing_address.country
    end
    
    def total_weight
      order_items.inject(BigDecimal(0)) { |t,i| t + i.total_weight}
    end

    def delivery_required?
      total_weight > BigDecimal(0)
    end
    # An array of all the delivery services which are suitable for this order in it's
    # current state (based on its current weight)
    def available_delivery_services
      delivery_service_prices.map(&:delivery_service).uniq
    end

    # Return the delivery price for this order in its current state
    #
    # @return [BigDecimal]
    def delivery_service_price
      self.delivery_service && self.delivery_service.delivery_service_prices.for_weight(self.total_weight).first
    end
    
    def delivery_service_prices
       if delivery_required?
         prices = DeliveryServicePrice.joins(:delivery_service).where(:delivery_services => {:active => true}).order(:price).for_weight(total_weight)
         prices = prices.select { |p| p.countries.empty? || p.country?(self.delivery_country) }
         prices.sort{ |x,y| (y.delivery_service.default? ? 1 : 0) <=> (x.delivery_service.default? ? 1 : 0) } # Order by truthiness
       else
         []
       end
    end
    # The recommended delivery service for this order
    def delivery_service
      super || available_delivery_services.first
    end
     # The price for delivering this order in its current state
    # def delivery_price
    #   delivery_service_price.try(:price) || BigDecimal(0)
    # end
    # The cost of delivering this order in its current state
    def delivery_cost_price
      delivery_service_price.try(:cost_price) || BigDecimal(0)
    end
    # The tax rate for the delivery of this order in its current state
    def delivery_tax_rate
      delivery_service_price.try(:tax_rate).try(:rate_for, self) || BigDecimal(0)
    end
    # Is the currently assigned delivery service appropriate for this order?
    def valid_delivery_service?
      self.delivery_service ? self.available_delivery_services.include?(self.delivery_service) : !self.delivery_required?
    end
    # Remove the associated delivery service if it's invalid
    def remove_delivery_service_if_invalid
      unless self.valid_delivery_service?
        self.delivery_service = nil
        self.save
      end
    end
    # The URL which can be used to track the delivery of this order
    def courier_tracking_url
      return nil if self.shipped_at.blank? || @courier_tracking_url ||= self.delivery_service.tracking_url_for(self)
    end
    # Mark this order as shipped
    def ship!
      run_callbacks :ship do
        self.shipped_at = Time.now
        self.state = 'shipped'
        self.save!
      end
    end

end

app/models/order/states.rb
class Order < ActiveRecord::Base
  
  # An array of all the available statees for an order
  STATES = ['building', 'confirming', 'received', 'accepted', 'rejected', 'shipped']

  # Validations
  validates :state, :inclusion => {:in => STATES}

  # Set the state to building if we don't have a state
  after_initialize  { self.state = STATES.first if self.state.blank? }
  #All orders which have been received
  scope :received, -> {where("received_at is not null")}
  # All orders which are currently pending acceptance/rejection
  scope :pending, -> { where(:state => 'received') }
  # All ordered ordered by their ID desending
  scope :ordered, -> { order(:id => :desc)}

   # Is this order still being built by the user?
    #
    # @return [Boolean]
    def building?
      self.state == 'building'
    end
  
    # Is this order in the user confirmation step?
    #
    # @return [Boolean]
    def confirming?
      self.state == 'confirming'
    end
  
    # Has this order been rejected?
    #
    # @return [Boolean]
    def rejected?
      !!self.rejected_at
    end
  
    # Has this order been accepted?
    #
    # @return [Boolean]
    def accepted?
      !!self.accepted_at
    end
  
    # Has the order been received?
    #
    # @return [Boolean]
    def received?
      !!self.received_at?
    end
    
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
	before_action :set_order, only: [:update, :destroy, :show, :accept, :reject, :ship]
	before_action :require_admin_user, except: [:update]
  before_action :require_user, only: [:update]
	layout 'admin'


	def index
		@orders = Order.ordered.page(params[:page]).per_page(30)
	end
    
    def show
    end

    def new
    	
    end

    def create
    	@order = Order.new(order_params)
	    if @order.save
	      flash[:success] = "A new order has been sent."
	      redirect_to admin_orders_path
	    else
	      flash[:alert] = "Something went wrong."
	      render action: 'new'
	    end
    end

    def update
      if @order.expired?
      	flash[:notice] = "Your order has expired, check out again."
	    redirect_to root_path
      else
      	if @order.update_attributes(order_params)
          @order.order_items.select(&:check_promo)
	 
          flash[:success] = "Please enter your payment details."
	    	  redirect_to purchase_path(token: @order.token)
	    else
          flash[:alert] = "Something went wrong."
          render action: 'edit'
        end
      end
    end

    def accept
    	@order.accept!
    	flash[:success] = "order # #{@order.id} has been accepted!"
    	redirect_to admin_order_path(@order)
    end

    def reject
      @order.reject!
      flash[:success] = "order # #{@order.id} has been rejected!"
      redirect_to admin_order_path(@order)
    end

    def ship
      @order.ship!
      flash[:success] = "order # #{@order.id} has been marked as shipped!"
      redirect_to admin_order_path(@order)
    end

	def destroy
		@order.destroy
        flash[:success] = "The order has been Deleted."
        redirect_to admin_orders_path
	end 

	private

	def set_order
		@order = Order.find(params[:id])
	end

	def order_params
	   params.require(:order).permit(:state, :accepted_at, :received_at, :delivery_service_id, :delivery_price, :rejected_at, :separate_delivery_address, :delivery_name, :delivery_postcode, :amount_paid, :customer_id, :billing_address_id, :shipping_address_id, :token, :promo_code )
	end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.haml
.cd-header.show
  =image_tag('order.svg', id:'ar-icon')
  =image_tag('hamburger.svg', id:'menu-trigger')
  %h3.mar-left-80 Orders
.row
  .large-2.columns
  .small-11.medium-11.large-10.columns
    %table.table
      %thead
        %tr
          %th{width: 100} Number
          %th{width: 200} Customer
          %th{width: 100} State
          %th{width: 150} Products
          %th{width: 110} Total(¥)
          %th{width: 90} Payment
          %th{width: 50} 
      %tbody
        - @orders.each do |order|
          %tr
            %td= link_to(order.id, admin_order_path(order))
            %td= order.customer.full_name
            %td{:class => "#{order.state}"}= order.state.capitalize
            %td
              - order.order_items.each do |item|
                = item.ordered_item.name.titleize + ", "
            %td
              - if order.received?
                = order.amount_paid.to_s
              - else
                = "0"
            %td
              - if order.payments.last.nil?
                = "----------"
              - else
                = order.payments.last.state
            %td.delete= link_to "Delete", admin_order_path(order), method: :delete, data: {confirm: "Are you sure you want to delete this order?"}
    .admin-page
      = will_paginate @orders

app/views/admin/orders/show.html.haml
.cd-header.show
  =image_tag('order.svg', id:'ar-icon')
  =image_tag('hamburger.svg', id:'menu-trigger')
  =link_to('back to orders', admin_orders_path, class: 'button small round dark header-btn')
  %h3.mar-left-80 Orders
.contain
  .row.show-order
    .large-6.small-6.columns
      .row
        .large-5.small-5.columns.large-offset-1
          %ul.show-order-left
            %li Customer
            - if @order.separate_delivery_address
              %li Billing Name
              %li Delivery Name
              %li Delivery Address
              %li Billing Address
            - else
              %li Bil/Del Name
              %li Bil/Del Address
        .large-6.small-6.columns
          %ul.show-order-right
            %li= link_to @order.customer.full_name, edit_admin_user_path(@order.customer)
            - if @order.separate_delivery_address
              %li= @order.billing_name
              %li= @order.shipping_name
              %li= @order.shipping_address.full_address + "; "
              %li= @order.billing_address.full_address
            - else
              %li= @order.billing_name
              %li= @order.billing_address.full_address
    .large-6.small-6.columns
      .row
        .large-5.small-5.columns.large-offset-1
          %ul.show-order-left
            %li Email address
            - if @order.separate_delivery_address
              %li Bil Telephone
              %li Del Telephone
            - else
              %li Telephone
            - if @order.received?
              %li Weight
              %li Delivery Service
        .large-6.small-6.columns
          %ul.show-order-right
            %li= @order.customer.email
            - if @order.separate_delivery_address
              %li= @order.billing_address.phone_number
              %li= @order.shipping_address.phone_number
            - else 
              %li= @order.billing_address.phone_number
            - if @order.received?
              %li= @order.total_weight.to_s + "g"
              %li= @order.delivery_service.name.capitalize
.row
  .small-11.medium-11.large-10.columns.large-offset-2
    %table.table
      %thead
        %tr
          %th{width: 250} Item
          %th{width: 200} Price/Variant(¥)
          %th{width: 200} quantity
          %th{width: 125} Weight
          %th{width: 125} Total
      - if @order.received? || @order.has_items?
        %tboby
          - @order.order_items.each do |item|
            %tr
              %td= item.ordered_item.name.capitalize
              %td= item.ordered_item.price
              %td= item.quantity
              %td= item.total_weight
              %td= item.total_cost
          %tr
            %td Total
            %td
            %td
            %td= @order.total_weight
            %td= @order.total_cost
.row
  .small-11.medium-11.large-10.columns.large-offset-2
    %table.table
      %thead
        %tr
          %th{width: 200} Payment Amount($)
          %th{width: 150} Method
          %th{width: 150} State
          %th{width: 250} Received at
          %th{width: 150} 
      %tboby
        - @order.payments.each do |payment|
          %tr
            %td= (Currency.find_by_locale("en").rate * payment.amount.to_i).to_i
            %td= payment.method
            %td= payment.state
            %td= payment.created_at.strftime("%m/%d/%y")
            %td.delete= link_to "Confirm", confirm_admin_payment_path(payment)
          %tr
            %td Total
            %td
            %td
            %td= @order.total_weight
            %td= @order.total_cost
.contain.last
  .row
    = link_to('ACCEPT', accept_admin_order_path(@order), class: 'button small success round header-btn')
    = link_to('REJECT', reject_admin_order_path(@order), class: 'button small dark round header-btn')
    = link_to('SHIP', ship_admin_order_path(@order), class: 'button small dark round header-btn')

       