config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :stock_level_adjustments
    resources :products
    resources :orders do
      member do
        get :ship
        get :accept
        get :reject
      end
    end
    resources :articles do
      member {post :like}
    end
    resources :promotions
    resources :tax_rates
    resources :users
    resources :countries
    resources :addresses
    resources :currencies
    resources :product_categories
    resources :payments, only: [:new, :create] do
      member do
        get :confirm
      end
    end
    resources :delivery_services do
      resources :delivery_service_prices
    end
  end
  resources :comments do
    member {post :like}
  end

  get '/admin', to: "admin/products#index"

  scope "(:locale)",locale: /#{I18n.available_locales.join("|")}/ do
  
    resources :user_sessions, only: [:new, :create]
    resources :password_resets
    get '/store/:permalink', to: "public#show", as: :item
    get '/home', to: "public#index", as: :home
    get '/store', to: "public#store", as: :store
    get "/login" => "user_sessions#new", as: :login
    get "/register" => "admin/users#register", as: :register
    get "/logout" => "user_sessions#destroy", as: :logout
    get 'user_sessions/create'
    get 'user_sessions/destroy'
    get '/cart', to: "cart#index", as: :cart
    get '/add', to: "cart#add", as: :add
    get '/clear', to: "cart#clear", as: :clear
    get '/remove', to: "cart#remove", as: :remove
    get '/set-address/(:delivery)/(:token)', to: "admin/addresses#new", as: :set_address
    get '/set-delivery/(:token)', to: "process#delivery", as: :set_delivery
    get '/blog', to: "blog#blog", as: :blog
    get '/blog/:permalink', to: "blog#article", as: :blog_article
    get '/about', to: "public#about", as: :about
    get '/contact', to: "public#contact", as: :contact
    get '/payment/:token', to: "admin/payments#new", as: :purchase
    get '/terms', to: "public#terms", as: :terms
    root 'public#index'
  end
  match '', to: redirect("/#{I18n.default_locale}/home"), :via => [:get]
  match 'admin/:controller(/:action(/:id))', :via => [:get, :post, :patch]

end

app/models/delivery_service.rb
class DeliveryService < ActiveRecord::Base
	# Validations
    validates :name, :presence => true
    validates :courier, :presence => true
  
    # Orders which are assigned to this delivery service
    has_many :orders, :dependent => :restrict_with_exception
    
    # Prices for the different levels of service within this delivery service
    has_many :delivery_service_prices, :dependent => :destroy
  
    # All active delivery services
    scope :active, -> { where(:active => true)}
    scope :ordered, -> { order(:created_at => :desc)}
    
    # Returns a tracking URL for the passed order

    # @return [String] the full URL for the order.
    def tracking_url_for(order)
      return nil if self.tracking_url.blank?
      tracking_url = self.tracking_url.dup
      tracking_url.gsub!("{{consignment_number}}", CGI.escape(order.consignment_number.to_s))
      tracking_url.gsub!("{{delivery_postcode}}", CGI.escape(order.delivery_postcode.to_s))
      tracking_url.gsub!("{{billing_postcode}}", CGI.escape(order.billing_postcode.to_s))
      tracking_url
    end
end

app/controllers/admin/delivery_services_controller.rb
class Admin::DeliveryServicesController < ApplicationController
  before_action :set_delivery_service, only: [:update, :edit, :destroy]
  before_action :require_admin_user
  layout 'admin'

  def index
  	@delivery_services = DeliveryService.ordered.page(params[:page]).per_page(30)
  end

  def new
  	@delivery_service = DeliveryService.new
  end

  def edit
  end

  def create
  	@delivery_service = DeliveryService.new(delivery_service_params)
  	if @delivery_service.save
      flash[:success] = "A new Delivery Service has been created."
      redirect_to admin_delivery_services_path
    else
      flash[:alert] = "Something went wrong."
      render action: 'new'
  	end
  end

  def update
  	if @delivery_service.update_attributes(delivery_service_params)
      flash[:success] = "The Delivery Service has been updated."
        redirect_to admin_delivery_services_path
      else
        flash[:alert] = "Something went wrong."
        render action: 'edit'
  	end
  end

  def destroy
    @delivery_service.destroy
    flash[:success] = "The Delivery Service has been Deleted."
    redirect_to admin_delivery_services_path
  end

  private

  def delivery_service_params
  	params.require(:delivery_service).permit(:name, :default, :active, :tracking_url, :courier)
  end

  def set_delivery_service
  	@delivery_service = DeliveryService.find(params[:id])
  end

end

app/helpers/admin/delivery_services_helper.rb
module Admin::DeliveryServicesHelper
end

app/views/admin/delivery_services/_form.html.haml
.contain
  .row
    .small-6.large-6.columns
      %label{:class => "#{error_on?(@delivery_service, :name)}"} Name
      = f.input :name, label: false
    .small-6.large-6.columns
      = f.input :code
.contain
  .row
    .small-6.large-6.columns
      = f.input :default, as: :boolean, label: "Sets this as default Delivery service when checked."
    .small-6.large-6.columns
      = f.input :active, as: :boolean, label: "Sets this as active when checked."
.contain
  .row
    .small-6.large-6.columns
      %label{:class => "#{error_on?(@delivery_service, :courier)}"} Courier
      = f.input :courier, label: false
    .small-6.large-6.columns
      = f.input :tracking_url
.contain.last
  .row
    = f.button :submit, "SAVE", class: 'button small round success header-btn'
    = link_to('CANCEL', admin_delivery_services_path(), class: 'button small dark round header-btn')
    

app/views/admin/delivery_services/edit.html.haml
.cd-header.show
  =image_tag('deliveries.svg', id:'ds-icon')
  =image_tag('hamburger.svg', id:'menu-trigger')
  =link_to('Back to services', admin_delivery_services_path(), class: 'button small round dark header-btn')
  %h3.mar-left-80 Delivery Services
= simple_form_for @delivery_service, url: url_for(:action => 'update', :controller => 'admin/delivery_services'), :method => 'patch' do |f|
  = render(:partial => 'form', :locals => {:f => f})

app/views/admin/delivery_services/index.html.haml
.cd-header.show
  =image_tag('deliveries.svg', id:'ds-icon')
  =image_tag('hamburger.svg', id:'menu-trigger')
  =link_to('new Delivery Sercice', new_admin_delivery_service_path(), class: 'button small round success header-btn')
  %h3.mar-left-80 Delivery Services
.row
  .large-2.columns
  .small-11.medium-11.large-10.columns
    %table.table
      %thead
        %tr
          %th{width: 200} Name
          %th{width: 200} Prices
          %th{width: 200} Courrier
          %th{width: 120} Active
          %th{width: 120} Default
          %th{width: 60}
      %tbody
        - @delivery_services.each do |d_service|
          %tr
            %td= link_to(d_service.name.capitalize, edit_admin_delivery_service_path(d_service))
            %td= link_to("Set prices", admin_delivery_service_delivery_service_prices_path(delivery_service_id: d_service))
            %td= d_service.courier
            %td= status_tag(d_service.active)
            %td= status_tag(d_service.default)
            %td.delete= link_to "Delete", admin_delivery_service_path(d_service), method: :delete, data: {confirm: "Are you sure you want to delete this Delivery Sercice?"}
    .admin-page
      = will_paginate @delivery_services

app/views/admin/delivery_services/new.html.haml
.cd-header.show
  =image_tag('deliveries.svg', id:'pr-icon')
  =image_tag('hamburger.svg', id:'menu-trigger')
  =link_to('Back to Services', admin_delivery_services_path(), class: 'button small round dark header-btn')
  %h3.mar-left-80 Delivery Services
= simple_form_for @delivery_service, url: admin_delivery_services_path(@delivery_service), method: :post do |f|
  = render(:partial => 'form', :locals => {:f => f})