config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :stock_level_adjustments
    resources :products
    resources :orders do
      member do
        get :ship
        get :accept
        get :reject
      end
    end
    resources :articles do
      member {post :like}
    end
    resources :promotions
    resources :tax_rates
    resources :users
    resources :countries
    resources :addresses
    resources :currencies
    resources :product_categories
    resources :payments, only: [:new, :create] do
      member do
        get :confirm
      end
    end
    resources :delivery_services do
      resources :delivery_service_prices
    end
  end
  resources :comments do
    member {post :like}
  end

  get '/admin', to: "admin/products#index"

  scope "(:locale)",locale: /#{I18n.available_locales.join("|")}/ do
  
    resources :user_sessions, only: [:new, :create]
    resources :password_resets
    get '/store/:permalink', to: "public#show", as: :item
    get '/home', to: "public#index", as: :home
    get '/store', to: "public#store", as: :store
    get "/login" => "user_sessions#new", as: :login
    get "/register" => "admin/users#register", as: :register
    get "/logout" => "user_sessions#destroy", as: :logout
    get 'user_sessions/create'
    get 'user_sessions/destroy'
    get '/cart', to: "cart#index", as: :cart
    get '/add', to: "cart#add", as: :add
    get '/clear', to: "cart#clear", as: :clear
    get '/remove', to: "cart#remove", as: :remove
    get '/set-address/(:delivery)/(:token)', to: "admin/addresses#new", as: :set_address
    get '/set-delivery/(:token)', to: "process#delivery", as: :set_delivery
    get '/blog', to: "blog#blog", as: :blog
    get '/blog/:permalink', to: "blog#article", as: :blog_article
    get '/about', to: "public#about", as: :about
    get '/contact', to: "public#contact", as: :contact
    get '/payment/:token', to: "admin/payments#new", as: :purchase
    get '/terms', to: "public#terms", as: :terms
    root 'public#index'
  end
  match '', to: redirect("/#{I18n.default_locale}/home"), :via => [:get]
  match 'admin/:controller(/:action(/:id))', :via => [:get, :post, :patch]

end

app/models/product.rb
class Product < ActiveRecord::Base
  # Add dependencies for products
  require_dependency 'product/product_attributes'
  require_dependency 'product/variants'

  #Attachments for this product
  has_many :attachments, :as => :parent, :dependent => :destroy, :autosave => true
  # The product's categorizations
  # has_many :product_categorizations, dependent: :destroy, inverse_of: :product
  # The product's categories
  belongs_to :product_category
  # Ordered items which are associated with this product
  has_many :order_items, dependent: :restrict_with_exception, :as => :ordered_item
  # Orders which contain this product
  has_many :orders, :through => :order_items
  # Stock level adjustments for this product
  has_many :stock_level_adjustments, :dependent => :destroy
  # Promotion if any
  belongs_to :promotion
  # Nested attributes for attachments
  accepts_nested_attributes_for :attachments, allow_destroy: true 
  # globalize gem initialization
  translates :name, :description
  #Validations
  validates :name, :presence => true
  validates :permalink, :presence => true, :uniqueness => true
  validates :weight, :numericality => true
  validates :price, :numericality => true


  # Before validation, set the permalink if we don't already have one
  before_validation { self.permalink = self.name.parameterize if self.permalink.blank? && self.name.is_a?(String) }
  before_validation { self.promo_price = self.price - self.promotion.rate * 0.01 * self.price if has_promotion }
 
  # All active Product
  scope :active, -> { where(active: true)}
  scope :ordered, -> { order(:created_at => :desc)}
  scope :category, -> (category) {where product_category_id: category}
  
  def orderable?
    return false unless self.active?
    return false if self.has_variants?
    true
  end

  #The price of the product
  def current_price
  	self.promoted ? self.promo_price : read_attribute(:price)
  end
  
  def in_stock?
    stock_control? ? stock > 0 : true
  end

  # Return the total number of items currently in stock
  def stock_lg
    self.stock_level_adjustments.sum(:adjustment_l) 
  end

  def stock_xl
    self.stock_level_adjustments.sum(:adjustment_xl)
  end

  def stock_xxl
    self.stock_level_adjustments.sum(:adjustment_xxl)
  end

  def stock_m
    self.stock_level_adjustments.sum(:adjustment_m)
  end
  
  def stock_sm
    self.stock_level_adjustments.sum(:adjustment_s)
  end

  def stock_xs
    self.stock_level_adjustments.sum(:adjustment_xs)
  end

  def total_stock
    stock_lg +  stock_xl + stock_xxl +  stock_m + stock_xs 
  end

  def stock(size)
    case size
    when 's'
      stock_sm
    when 'm'
      stock_m
    when 'l'
      stock_lg
    when 'xl'
      stock_xl
    when 'xxl'
      stock_xxl
    when 'xs'
      stock_xs
    end
  end
  
  def has_attachments?
    self.attachments.count > 0 
  end
  
  def has_promotion
    !self.promotion.nil?
  end

  def has_at_least_one_product_category
    errors.add(:base, 'must add at least one product category') if self.product_categories.blank?
  end

end

app/models/product/product_attributes.rb
class Product < ActiveRecord::Base
  
end

app/models/product/variants.rb
class Product < ActiveRecord::Base
  # Validations
  validate {error.add :base, :can_belong_to_root if self.parent && self.parent.parent }
  has_many :variants, :class_name => 'Product', :foreign_key => 'parent_id', :dependent => :destroy

  # The parent product (only applies to variants)
  belongs_to :parent, :class_name => 'Product', :foreign_key => 'parent_id'
  # All products which are not variants
  scope :root, -> { where(:parent_id => nil) }

  # Does this product have any variants?
  def has_variants?
    !variants.empty?
  end

  # Returns the default variant for the product or nil if none exists.
  def default_variant
    return nil if self.parent
    @default_variant ||= self.variants.select { |v| v.default? }.first
  end
  
  # Is this product a variant of another?
  def variant?
    !self.parent_id.blank?
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
	before_action :set_product, only: [:update, :edit, :destroy]
  before_action :require_admin_user
  layout 'admin'

	def index
	  @products = Product.ordered.page(params[:page]).per_page(30)
	end

	def new
	  @product = Product.new 
	end

  def edit
  end

	def create
	  @product = Product.new(product_params)
 	  respond_to do |format|
        if @product.save
          @product.stock_level_adjustments.create(description: 'Initial stock')
          if params[:images]
            params[:images].each {|image|
              @product.attachments.create(file: image, parent_type: 'product')
            }
          end
          format.html { 
            flash[:success] = "A new product has been created."
            redirect_to admin_products_path
          }

          format.js
        else
          format.html { 
            flash[:alert] = "Something went wrong."
            render action: 'new'
          }
          format.js
        end
	  end
	end

	def update
	  if @product.update_attributes(product_params)
        if params[:images]
          params[:images].each {|image|
            if !(@product.attachments.find_by_file_name(image.original_filename[0..-5].to_s).nil?)
              @product.attachments.find_by_file_name(image.original_filename[0..-5].to_s).destroy 
            end
            @product.attachments.create(file: image, parent_type: 'product')
          }
        end
        flash[:success] = "The product has been updated."
        redirect_to admin_products_path
      else
        flash[:alert] = "Something went wrong."
      	render action: 'edit'
	  end
	end

  def destroy
    @product.destroy
    flash[:success] = "The Product has been Deleted."
    redirect_to admin_products_path
  end

	private
     
    def product_params
      params.require(:product).permit(:name, :permalink, :description, :active, :weight, :price, :promo_price, :promoted, :promotion_id, :stock_control, :product_category_id)
    end

    def set_product
      @product = Product.find(params[:id])  
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.haml
.contain
  .row
    .small-12.large-12.columns
      = f.input :product_category_id, collection: ProductCategory.all, label_method: :name
  .row
    .small-4.large-4.columns
      %label{:class => "#{error_on?(@product,:name)}"} Name
      = f.input :name, label: false
    .small-4.large-4.columns
      %label{:class => "#{error_on?(@product,:permalink)}"} Permalink
      = f.input :permalink, label: false
    .small-4.large-4.columns
      %label{:class => "#{error_on?(@product,:price)}"} Price
      .input-group
        %span.input-group-label ¥
        = f.input_field :price, class: 'input-group-field', type: 'number'
  .row
    .small-12.large-12.columns
      = f.input :description, as: :text
.contain
  .row
    .small-6.large-6.columns
      = f.input :promoted, as: :boolean, checked_value: true, unchecked_value: false, label: 'When Checked the promo price will be displayed.'
    .small-3.large-3.columns
      = f.input :promotion_id, collection: Promotion.all, label_method: :rate
    .small-3.large-3.columns
      = f.input :promo_price
.contain
  .row
    .small-6.large-6.columns
      = f.input :stock_control, as: :boolean, checked_value: true, unchecked_value: false, label: 'When checked the stock levels will be considered.'
    .small-6.large-6.columns
      %label{:class => "#{error_on?(@product,:weight)}"}Weight
      .input-group
        %span.input-group-label g
        = f.input_field :weight, class: 'input-group-field', type: 'number'
.contain
  .row
    = f.label "Product images"
  .p-images.row
    - if @product.has_attachments?
      - @product.attachments.each do |attachment|
        .p-image
          = img_tag(attachment)
          %p= attachment.file_name
    - else 
      %p.no-file Upload The appropriate product images (eg: front.jpg, back.jpg, detail_front_lg.jpg, detail_back_lg.jpg, detail_back.jpg)
  .row
    = file_field_tag "images[]", type: :file, multiple: true
.contain
  .row
    .small-6.large-6.columns
      = f.input :active, as: :boolean, checked_value: true, unchecked_value: false, label: 'Set the produt status as active when checked.'
    .small-6.large-6.columns
      = f.input :parent_id, collection: Product.all, label_method: :name

.contain.last
  .row
    = f.button :submit, "SAVE", class: 'button small round success header-btn'
    = link_to('CANCEL', admin_products_path(), class: 'button small dark round header-btn')

    

app/views/admin/products/edit.html.haml
.cd-header.show
  =image_tag('products.svg', id:'pr-icon')
  =image_tag('hamburger.svg', id:'menu-trigger')
  =link_to('back to products', admin_products_path(@product), class: 'button small round dark header-btn')
  = admin_locale_tag
  %h3 Products
= simple_form_for @product, html: {multipart: true}, url: url_for(:action => 'update', :controller => 'admin/products'), :method => 'patch' do |f|
  = render(:partial => 'form', :locals => {:f => f})

  

app/views/admin/products/index.html.haml
.cd-header.show
  =image_tag('products.svg', id:'pr-icon')
  =image_tag('hamburger.svg', id:'menu-trigger')
  =link_to('new product', new_admin_product_path(), class: 'button small round success header-btn')
  %h3 Products
.row
  .small-11.medium-11.large-10.columns.large-offset-2
    %table.table
      %thead
        %tr
          %th{width: 300} Name
          %th{width: 300} Price/Variant(¥)
          %th{width: 250} Stock
          %th{width: 50}
      %tboby
        - @products.each do |product|
          %tr
            %td= link_to(product.name, edit_admin_product_path(product))
            %td= product.price
            %td{:class => "stock #{ stock_status(product.total_stock)}"}
              = product.total_stock
              = link_to_image('pencil.svg', new_admin_stock_level_adjustment_path(product_id: product.id) , remote: true, data: { reveal_id: 'modal', product_id: product.id}, class: 'pencil')
            %td.delete= link_to "Delete", admin_product_path(product), method: :delete, data: {confirm: "Are you sure you want to delete this product?"}
    .admin-page
      = will_paginate @products

app/views/admin/products/new.html.haml
.cd-header.show
  =image_tag('products.svg', id:'pr-icon')
  =image_tag('hamburger.svg', id:'menu-trigger')
  =link_to('back to products', admin_products_path(), class: 'button small round dark header-btn')
  = admin_locale_tag
  %h3 Products
= simple_form_for :product, html: {multipart: true}, url: admin_products_path(@product), method: :post do |f|
  = render(:partial => 'form', :locals => {:f => f})